services:
  aicode:
    image: ${DOCKER_REGISTRY-}aicode
    build:
      context: .
      dockerfile: AICode/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
  products.database:
    image: postgres:latest
    container_name: products.database
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/products-db:/var/lib/postgresql/data
    ports:
      - 5433:5432
