services:
  aicode:
    image: ${DOCKER_REGISTRY-}aicode
    build:
      context: .
      dockerfile: AICode/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
  products.database:
    image: postgres:latest
    container_name: products.database
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  products.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'