services:
  aicode:
    image: ${DOCKER_REGISTRY-}aicode
    build:
      context: .
      dockerfile: AICode/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
  expense.db:
    image: postgres:latest
    container_name: expense.db
    environment:
      - POSTGRES_DB=user_Expense
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  products.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'